repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.4
  hooks:
  # Run the linter.
  - id: ruff
    types_or: [ python, pyi ]
    args: [ --fix ]
    files: ^autoemulate/|^tests/|^benchmarks/
  # Run the formatter.
  - id: ruff-format
    types_or: [ python, pyi ]
    files: ^autoemulate/|^tests/|^benchmarks/
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.398
  hooks:
  - id: pyright
    files: ^autoemulate/|^tests/|^benchmarks/
