repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.0
  hooks:
  # Run the linter.
  - id: ruff
    types_or: [ python, pyi, jupyter ]
    args: [ --fix ]
    files: ^autoemulate/|^tests/|^benchmarks/|^docs/tutorials/
  - id: ruff-format
    types_or: [ python, pyi, jupyter ]
    files: ^autoemulate/|^tests/|^benchmarks/|^docs/tutorials/

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.405
  hooks:
  - id: pyright
    files: ^autoemulate/|^tests/|^benchmarks/
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
  - id: nbstripout
    exclude: ^case_studies/
