# Project Metadata
name = "autoemulate"
version = "0.1.0"
description = "An emulator platform for Digital Twins"
license = "MIT"
authors = ["martin stoffel <martin.adam.stoffel@gmail.com>"]
readme = "README.md"

# Dependencies
[dependencies]
python = ">=3.10,<3.13"
mogp-emulator = "^0.7.2"
matplotlib = "^3.7.2"
pytest = "^7.4.0"
scikit-learn = "^1.3.0"
sphinx = "^7.2.6"
myst-parser = "^2.0.0"
furo = "^2023.9.10"
sphinx-copybutton = "^0.5.2"
sphinx-autodoc-typehints = "^1.24.0"
coverage = "^7.3.1"
pandas = "^2.1.1"

# Dev Dependencies
[dev_dependencies]
ipykernel = "^6.25.0"

# Extras
[extras]
docs = ["furo", "sphinx-copybutton", "sphinx-autodoc-typehints"]
